### ISSUE TITLE
一个点初始连接多个点 应该如何操作

### ISSUE THREAD

**Issue by tianweicc** [wangduanduan/jsplumb-chinese-tutorial#1]
一个点初始连接多个点 应该如何操作

**Comment by wangduanduan** [comment]
参考：https://wdd.js.org/jsplumb-chinese-tutorial/#/?id=_217-%E4%B8%80%E4%B8%AA%E7%AB%AF%E7%82%B9%E5%A6%82%E4%BD%95%E6%8B%96%E6%8B%BD%E5%87%BA%E5%A4%9A%E6%9D%A1%E8%BF%9E%E7%BA%BF


默认情况下，maxConnections的值是1，也就是一个端点最多只能拉出一条连线。

你也可以设置成其他值，例如5，表示最多可以有5条连线。

如果你想不限制连线的数量，那么可以将该值设置为-1

```
var common = {
  isSource: true,
  isTarget: true,
  connector: ['Straight'],
  maxConnections: -1
}

jsPlumb.addEndpoint('item_left', {
  anchors: ['Right']
}, common)
```
