### ISSUE TITLE
多个click事件怎么停止事件传播

### ISSUE THREAD

**Issue by richard1225** [wangduanduan/jsplumb-chinese-tutorial#20]
jspInstance绑定了边的click事件， 同时#container也onclick了一个事件，单击时，两个click事件都会触发，e.stopPropagation并没有用

不知道能否只让边的click生效呢？

**Comment by wangduanduan** [comment]
可能性1: stopPropagation用的不对，你需要查查这个方法是如何处理的。

即使真的stopPropagation真的无法阻止事件传播，会触发两次事件。但是我认为可以从click事件的事件源去判断，只处理来自边的click事件。
