### ISSUE TITLE
大佬，官网的流程图整体的缩放、放大、拖拽效果有吗？

### ISSUE THREAD

**Issue by Dawnxiaozhao** [wangduanduan/jsplumb-chinese-tutorial#28]
https://jsplumbtoolkit.com/demonstration/flowchart-builder

**Comment by wangduanduan** [comment]
dev-tools工具打开看看人家怎么实现的不就知道了吗？

都是css控制的。

**Comment by Dawnxiaozhao** [comment]
没看懂啊，能做个小案例吗？大佬
