### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by greendayzz** [wangduanduan/jsplumb-chinese-tutorial#6]
请问：当我使用了addEndpoint，并将isSource和isTarget设置为true后，我设置拖动，只能拖动锚点，不能拖动节点，这是什么原因呢？麻烦解答一下，谢谢

**Comment by wangduanduan** [comment]
参考 2.2. 可拖动节点

```js
jsPlumb.draggable('item_left')
```

**Comment by greendayzz** [comment]
好的，我去看看~谢谢~




------------------ 原始邮件 ------------------
发件人: "wang duanduan"<notifications@github.com>;
发送时间: 2019年5月28日(星期二) 下午2:51
收件人: "wangduanduan/jsplumb-chinese-tutorial"<jsplumb-chinese-tutorial@noreply.github.com>;
抄送: "greenday"<425027072@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wangduanduan/jsplumb-chinese-tutorial] 请教一个问题 (#6)




参考 2.2. 可拖动节点
 jsPlumb.draggable('item_left')
